---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/suppliers/":
    get:
      summary: Retrieves a supplier
      tags:
      - Supplier
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: name found
          schema:
            type: object
            properties:
              supplierName:
                type: string
              contactName:
                type: string
              address:
                type: string
              city:
                type: string
              postalCode:
                type: string
              country:
                type: string
              phone:
                type: string
            required:
            - supplierName
            - contactName
            - address
            - city
            - postalCode
            - country
            - phone
        '404':
          description: supplier not found
